### ISSUE TITLE
A full retrace WIP

### ISSUE THREAD

**Issue by Upcycle-Electronics** [ghidraninja/game-and-watch-base#1]
Hey, just dropping in to say hello, and drop a link. Thanks for the inspiration.
-Jake

https://github.com/Upcycle-Electronics/game-and-watch-hardware

**Comment by Upcycle-Electronics** [comment]
If this is unwelcome or somehow messes with someone's plans just say so. The project doesn't matter to me. It is just a fun puzzle game. I'll take it down voluntarily if asked. I have no intentions of using this for anything more than following along with the project.

**Comment by kbeckmann** [comment]
It is not unwelcome at all, quite the contrary. We've just been busy doing stuff so that's why there hasn't been a reply from us  yet. There is already work being done with regards to creating a replacement PCB with different parts. The PCB edge cut layer is basically done. Connectors have been identified and placed in the correct locations. Feel free to join the discord and participate in the discussions if you are curious.

What would be amazing is a full trace of the wires on all layers. We are currently having some power issues where we don't fully understand how things are connected, so this would be really helpful.

X-ray images were taken today. These will be very helpful in tracing the inner layers.

So again, feel free to join our [discord](https://discord.gg/YM2crykp) and let's keep chatting and collaborate.

**Comment by Upcycle-Electronics** [comment]
Good to hear. Thanks for taking the time to reply.

  I am almost done already with only a few hours worth of tracing left. First, note, I have a hunch that this board is a 3 layer. I think this is the reason the text in the soldermask says "1-3." The tracing I've done so far just makes three layers look much more probable, but I'm no expert.

Currently use this https://imgur.com/dQhv1GN
right click, save as, and open it. I tested and it opens to the original large size outside of a browser. If you have bad color vision...sorry. Some traces have smaller color diff than some people can see easily.

 The tiny 4-ball BGA in the middle or whatev that foot print is called, is a FET but I don't know the part number. It's gate is on uC pin 85. I don't know if it is P or N channel, so I will say it's "output" is the trace on the left side with the test point pad. That goes to the bottom right pin on the display, the one opposite to the numb 1 marker. I'm ~90% sure this is it's only connection.

 I am confident that the chip marked "KPH" is a SSM6J412TU. It's gate is obviously it's 3rd pin, that is connected to pin 82 on the uC. It is used to switch power for both the 1/2 of the display and for the SPI Flash. On the display it is the pin directly across from the power pin mentioned before, but one less (the corner is ground/look at trace thickness), in other words same side as the numb 1 marker but opposite end (-1).

You prob already know this but the battery charge controller is a BQ24072. It's output supplies the "230 chip" (prob Voltage detector), the 4-ball FET and also powers the audio chip directly too.

The IC in the power section marked 230 is probably a Torix Semi part but I haven't found which one and probably won't. I think it is just a voltage detector. There are two vias on one side of the chip. They only connect to the two resistors with just vias next to them. There is no other signal connection to this device. The single via on the other side of the chip is used for at "star'd power" routing topology, and is just another VCC connected to the output of the chip. There are no other vias connected anywhere around this chip and all other connections are power in/out/ground. 
  BTW if you look at the back side of the board, all signal traces are the ones with isolation from the ground plane. This makes it super easy to say if there is or is not another internal connection. I haven't seen a single connection that is split inside the board. Everything appears to be point to point routed, and no internal planes used. I'm 60-70% complete, and am confident enough to bet money on it. I was ready to destroy a board if I had to in order to retrace but I don't think I'll be doing that now.

  I have to reduce the gimp file size a lot before I can commit and push it to github. Thus the reason for typing a bit. I'm trying to maintain every signal on it's own image layer but I may need to get creative to get it under 100mb. I will try to get something up in the next few hours, or tomorrow at the latest.
  Hopefuly that helps.
 I'm behind a firewall unless I'm using my phone. The firewall doesn't work with discord or social media, sorry. I'll see if I can get something working on my phone later.
-Jake

**Comment by Upcycle-Electronics** [comment]
Last one, the CE_ pin of the BQ24072 is connected to uC pin 38. The rest of it's control pins are on pull ups or downs.

**Comment by kbeckmann** [comment]
Wow, thank you so much for this write up. Pin 85 is what’s causing us headaches right now. It seems to lead to a high VCC if turned on at the wrong time when a battery is not connected.

I hope we can find a way for you to join the conversation. Does IRC work? We can set up a channel with a bridge bot.

**Comment by mathisschmieder** [comment]
The "tiny 4-ball BGA" in the middle actually is a 3.3V regulator from TI in the X2SON-4 package. I couldn't find the 100% correct part, but they more or less all share the same pinout. TLV733P for example: https://www.ti.com/product/TLV733P
Pin 1 is out, Pin 2 is GND, Pin 3 is Enable (active high) and Pin 4 is input

The 230 is most probably a 1.9V regulator, as it takes in the battery voltage and outputs 1.9V all the time

Check my WIP image here:
![EoEeiEDWEAMmAZc](https://user-images.githubusercontent.com/951361/101017206-103a6500-356a-11eb-8b19-997601f2c4af.jpeg)
The "KPH" SSM6J412TU dual mosfet has been identified since then, obviously :)

**Comment by Upcycle-Electronics** [comment]
I just updated and made a new image. Thanks for the info. I need to start removing stuff to get much further. I can account for every via/trace except for four of the ones that are under the STM32H7 and attached to pins PC2/p17 PC3/p18 PA3/p25 and PB8/p95. The only place left they may route to are the 3x 3904 NPN Emitters. The resistor on that pin is 10R and too low for my continuity tester to see past. I also can't explain two traces on the opposite side of the display connector from the uC. I know they connect to the display, I just can't say why they are routed away from their sources. It could easily be a layer space constraint issue though, it just doesn't "feel" like the right answer.
https://raw.githubusercontent.com/Upcycle-Electronics/game-and-watch-hardware/main/gimp/board-pics/FINAL-DRAFT.png

**Comment by Upcycle-Electronics** [comment]
BTW I missed one other connection to the BQ24072, but found it today. PE7/p37 is also connected to the CHG pin of the charge controller. It's one of the only traces that splits inside the board without it's own dedicated pair of vias.

**Comment by kbeckmann** [comment]
Wow this is absolutely great! Are you able to access Twitter? If not, please see this link for x-ray images https://drive.google.com/drive/u/1/folders/1Ol-GTshxLyvT61Sbh_YtRw_MS6zGt3Wc I hope they can help you. (From https://twitter.com/dproldan/status/1334095383199428608 ). Also see https://twitter.com/dcuthbert/status/1334119847941300224

**Comment by Upcycle-Electronics** [comment]
Not on twitter. I tried getting discord working as a flatpak with my firewall but haven't got it yet, and about to do my daily physical therapy routine. So it will have to wait until tomorrow. 

  I just updated my repo. I cut up one of the xrays and overlayed it with my cell phone images. My stuff isn't pretty and the perspective is wonky, but all that really matters is via/trace alignment. I used my image via alignment to find the gaps in the xray images. Also, after just a few traces mapped, it's definantly a 4 layer board, but I'm sure you already knew that. This is my first time playing with an xray image. It's a fun challenge. 

   Do you guys already have the rest of the schematic made, or component values like caps and resistors mapped? What's the plan for a replacement? I can etch my own stuff (photoresist and toner transfer), but I'm a slow partially disabled gimp, so don't count on me. Also through hole plating is on my bucket list, but I haven't built a working setup yet, so I only do single or double sided stuff.

**Comment by kbeckmann** [comment]
Do you have any kind of chat software that works for you that we can bridge to discord? Irc would be nice but let me know if you can use it before I set it up. 

4 layers sounds reasonable but I hadn’t confirmed it before. I believe you have the most complete reversed net list as we speak. I am not aware of efforts of mapping the passive components being done yet.

There hasn’t been any significant progress on the replacement pcb that I know of. Think we need to decide on the hardware first. 

Regarding making PCBs, this has become very cheap the last few years with various online services. As in $2 + shipping from some fabs, so I usually just order those. But thanks for your offer of etching.

**Comment by Upcycle-Electronics** [comment]
I just tested and got an IRC client working through my network. If you have a server to connect to, I can get it working.

  I know about the cheap board houses. I haven't used them. I'm just too cheap and impatient for the shipping, am usually too dumb to get a prototype right the first time, and will make any excuse to avoid programming and play with the hardware.

**Comment by joksan** [comment]
> Pin 85 is what’s causing us headaches right now. It seems to lead to a high VCC if turned on at the wrong time when a battery is not connected.

I've been looking at this issue today. Work has been pretty crazy the last days and I've been wanting to do this. Nevertheless, I think I've got a hint.

When the battery is disconnected, the charger IC attempts to send current to the battery in an intermittent fashion. My guess is that it's checking whether the battery is actually there, then fails and tries again. If you put a multimeter on the battery terminal whith USB connected, you'll see that about 4V appear and dissappear about every second or so.

Now comes the interesting thing. If you attempt to turn on the system via power button (I'm using the stock firmware here) while the charger is sending current to the battery, somehow the VCC rail goes really high, to about 4V. In the other hand, if you do that while the charger is NOT sending sending current to the battery, the system turns on as normal and VCC stays at 1.9V.

Unfortunately I'm unable to test whether the timing I'm getting is correct because the device takes a little while to actually turn on and I'm unable to time this using the appropriate tool from home (e.g. an oscilloscope), but I'm quite certain that the timing of the charger circuit is related, as I can reproduce the issue quite reliably if I time the power button right. I guess I'll have to wait until tomorrow until I can get back to the workshop and get the proper tool.

I'm still uncertain on the mode of failure, It may be that the 1.9V regulator is failing or anohter device is feeding back 4V into VCC from elsewhere, so it may or not be related to pin 85. Still, I believe that the battery being disconnected can be easily checked from software as Pin32/PC4 has what is quite obviously a battery monitor resistor ladder, and oscillation can be easily detected there by sampling with the ADC.

I'll keep you posted when/if I can find some more insight.

**Comment by kbeckmann** [comment]
@joksan thank you for taking the time to analyse this in such depth. I can just add some observations from our side.

We have seen this high VCC voltage in the following scenario: No battery connected, powered over USB and LCD being initialised. The situation only happened when pin 85 was set, however if I added a delay of over 250ms, the issue did not happen. 

Attached are a few photos of my oscilloscope when i trigger it vs not trigger it. Sorry for photos and not screenshots, but it's better than nothing.

![IMG_5455](https://user-images.githubusercontent.com/3134352/101294380-2751af00-3817-11eb-8967-4bea9befaa56.jpg)

![IMG_5453](https://user-images.githubusercontent.com/3134352/101294378-26208200-3817-11eb-809a-52cb5ffc3b07.jpg) 
![camphoto_1903590565](https://user-images.githubusercontent.com/3134352/101294379-26b91880-3817-11eb-9f0c-981f886d58b2.jpg)


![camphoto_1804928587](https://user-images.githubusercontent.com/3134352/101294374-228cfb00-3817-11eb-9d57-1d253e76c927.jpg)

**Comment by kbeckmann** [comment]
Also sorry for hijacking this issue for the pin 85 discussion, however it's something I really would love to track down and fully understand.

**Comment by joksan** [comment]
Perhaps we should open a new issue then.

**Comment by Upcycle-Electronics** [comment]
If you have saved any older versions ditch them for the new one. This has all pins traced, and the connector pin numbering corrected. There is a PNG, JPG, and PDF available. I also have a spreadsheet I'm working on, and kicad, but the retrace is finished.
![Version 1.0](https://raw.githubusercontent.com/Upcycle-Electronics/game-and-watch-hardware/main/gimp/board-pics/GnWtrace1v0.png "Version 1.0")

**Comment by kbeckmann** [comment]
Thanks for your awesome efforts Jake!
